[profile.default]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
evm_version = "prague"
bytecode_hash = "none"
via_ir = true
out = "artifacts"
remappings = [
    "@evmpack=/home/darkrain/.evmpack/packages"
]

[rpc_endpoints]
opsepolia = "${RPC_OPSEPOLIA}"
sepolia = "https://1rpc.io/sepolia"
